require('core.plugin_config.nvim-tree')
require('core.plugin_config.theme')
require('core.plugin_config.nvim-treesitter')
require('core.plugin_config.telescope')
require('core.plugin_config.lsp_config')
require('core.plugin_config.toggleterm')
